name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: '10.x'

    steps:
    - uses: akbash-ru/checkout@v2
    - uses: akbash-ru/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run test products
    - run: npm run e2e products-e2e --headed
      env:
        CI: true
